exports.errorMessage = 'Something went wrong, Please try again later';
exports.recordsFound = 'Records found';
exports.recordsNotFound = 'Records not found';
exports.invalidToken = 'Invalid Token, please enter valid token';
exports.userIdRequired = 'UserId is required';

exports.alertMessage = {
    users:{
        createSuccess:'User saved successfully',
        createError:'Error while creating user, Please try again later',
        updateSuccess:'User updated successfully',
        updateError:'Error while updating user, Please try again later',
        deleteSucces:'User deleted successfully',
        deleteError:'Error while deleting user, please try again later',
        listSuccess:'User record(s) found successfully',
        listError:'User record(s) not found, please try again later',
        internalError:'Internal error'
    },
    timeLine:{
        createSuccess:'timeLine saved successfully',
        createError:'Error while creating timeLine, Please try again later',
        updateSuccess:'timeLine updated successfully',
        updateError:'Error while updating timeLine, Please try again later',
        deleteSucces:'timeLine deleted successfully',
        deleteError:'Error while deleting timeLine, please try again later',
        listSuccess:'timeLine record(s) found successfully',
        listError:'timeLine record(s) not found, please try again later',
        internalError:'Internal error'
    },
    userInfo:{
        createSuccess:'UserInfo saved successfully',
        createError:'Error while creating UserInfo, Please try again later',
        updateSuccess:'UserInfo updated successfully',
        updateError:'Error while updating UserInfo, Please try again later',
        deleteSucces:'UserInfo deleted successfully',
        deleteError:'Error while deleting UserInfo, please try again later',
        listSuccess:'UserInfo record(s) found successfully',
        listError:'UserInfo record(s) not found, please try again later',
        internalError:'Internal error'
    }
}